### ISSUE TITLE
定位数据不对

### ISSUE THREAD

**Issue by 979881765** [amap-demo/amap-location-flutter#10]
定位之后的 cityCode: , adCode:  不正确，按理应该是行政区域编码吧，不应该是城市名称。
另外是否可以把 省、市、区的adCode(行政区域编码都返回)

**Comment by roylly** [comment]
对应问题已修复，感谢反馈！

**Comment by roylly** [comment]
另外是否可以把 省、市、区的adCode(行政区域编码都返回)
对于这个问题，编码只有两级，cityCode和adCode；省和直辖市没有编码，直接返回了省的名称；
