### ISSUE TITLE
单次定位的例子

### ISSUE THREAD

**Issue by neutralino-ai** [amap-demo/amap-location-flutter#11]
能否提供单次定位的例子？我需要设计一个app，只需要在用户注册的时候拉取用户所在的城市和邮政编码，不需要实时追踪用户的位置；或者在用户单击定位时拉取当前位置。

**Comment by libingspace** [comment]
同求。我也需要单次定位的接口。谢谢大侠

**Comment by neutralino-ai** [comment]
> 同求。我也需要单次定位的接口。谢谢大侠

我研究了一下，如果只是需要GPS定位，那么可以用“location 包”，然后调用REST API以http的方式得到位置编码。

**Comment by libingspace** [comment]
> > 同求。我也需要单次定位的接口。谢谢大侠
> 
> 我研究了一下，如果只是需要GPS定位，那么可以用“location 包”，然后调用REST API以http的方式得到位置编码。

你这个方式应该不精确。最好还是用原生的吧

**Comment by neutralino-ai** [comment]
> > > 同求。我也需要单次定位的接口。谢谢大侠
> > 
> > 
> > 我研究了一下，如果只是需要GPS定位，那么可以用“location 包”，然后调用REST API以http的方式得到位置编码。
> 
> 你这个方式应该不精确。最好还是用原生的吧

我说的这个包 https://pub.dev/packages/location 。精度为什么会有区别？

**Comment by libingspace** [comment]
> > > > 同求。我也需要单次定位的接口。谢谢大侠
> > > 
> > > 
> > > 我研究了一下，如果只是需要GPS定位，那么可以用“location 包”，然后调用REST API以http的方式得到位置编码。
> > 
> > 
> > 你这个方式应该不精确。最好还是用原生的吧
> 
> 我说的这个包 https://pub.dev/packages/location 。精度为什么会有区别？

哥，这个包默认用的google地图定位，你确定你定位了？  是什么坐标？

**Comment by neutralino-ai** [comment]
> > > > > 同求。我也需要单次定位的接口。谢谢大侠
> > > > 
> > > > 
> > > > 我研究了一下，如果只是需要GPS定位，那么可以用“location 包”，然后调用REST API以http的方式得到位置编码。
> > > 
> > > 
> > > 你这个方式应该不精确。最好还是用原生的吧
> > 
> > 
> > 我说的这个包 https://pub.dev/packages/location 。精度为什么会有区别？
> 
> 哥，这个包默认用的google地图定位，你确定你定位了？ 是什么坐标？

非常抱歉让你感觉到不适。目前我已经切换解决方案了。该问题关闭吧。
