### ISSUE TITLE
the 'pods-runner' target has transitive dependencies that include statically linked binaries

### ISSUE THREAD

**Issue by cikichen** [amap-demo/amap-location-flutter#14]
the 'pods-runner' target has transitive dependencies that include statically linked binaries: (xxxx/ios/Pods/AMapLocation/AMapLocationKit.framework)

flutter: 1.22.4

```
  amap_location_flutter_plugin:
    git:
      url: https://github.com/amap-demo/amap-location-flutter.git
```

iOS编译不通过，直接报错，注释use_frameworks!不可取，因为其他插件需要依赖

**Comment by hadisi5216** [comment]
这位仁兄，请问问题有解决么。我遇到同样的问题

**Comment by cikichen** [comment]
> 这位仁兄，请问问题有解决么。我遇到同样的问题

搞不定，已经弃用了

**Comment by idootop** [comment]
加一，搞不定～

**Comment by idootop** [comment]
![图片](https://user-images.githubusercontent.com/35302658/102201423-0ec15300-3f01-11eb-94ac-7fc0f87b764e.png)
