### ISSUE TITLE
啥时候能发布到pub.dev上？

### ISSUE THREAD

**Issue by physiclaw** [amap-demo/amap-location-flutter#17]

**Comment by roylly** [comment]
官网正式版本已经发布到pub，对应名称为 amap_flutter_location ,请搜索和使用该插件库，同时还有地图的插件库amap_flutter_map，一同发布;

**Comment by physiclaw** [comment]
在pub上给你们点了赞，百度的定位SDK在iOS14编译失败，高德的第一次就成功了，以后就用你们的了。你们的SDK接口要比百度好用，可以看出很用心啊，赞一个，再接再厉~

**Comment by physiclaw** [comment]
pub上分数75分，建议修改一下更符合dart的规范，达到110分，这样用户就更多了
