### ISSUE TITLE
iOS 端定位失败，通道无信息返回

### ISSUE THREAD

**Issue by Mocaris** [amap-demo/amap-location-flutter#20]
iOS真机调试，手机状态显示定位中，无flutter 通道无定位信息返回

**Comment by xcc3641** [comment]
是解决了吗？我这里也遇到了 iOS 没有信息返回，可以告知如何解决的吗？

**Comment by Mocaris** [comment]
> 是解决了吗？我这里也遇到了 iOS 没有信息返回，可以告知如何解决的吗？

我这边是将返回信息转dart对象时出错了才没有看到信息返回，ios和android返回的定位信息有时会有出入

**Comment by xcc3641** [comment]
> > 是解决了吗？我这里也遇到了 iOS 没有信息返回，可以告知如何解决的吗？
> 
> 我这边是将返回信息转dart对象时出错了才没有看到信息返回，ios和android返回的定位信息有时会有出入

神奇，我这里是在 onLocationChange 里打印，iOS 就没有反应，Android 是好的。
