### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries

### ISSUE THREAD

**Issue by VitoJIanxue** [amap-demo/amap-location-flutter#4]
老铁，pod引入不好使呢，pod失败。还有本地引入能详细点吗

**Comment by roylly** [comment]
具体什么错误呢？

**Comment by ziuyung** [comment]
@roylly 

[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (***/example/ios/Pods/AMapLocation/AMapLocationKit.framework)

因为要支持swift  pod 使用 use_frameworks!
去掉这个 use_frameworks!可以Pod，但新flutter 要改必须 use_frameworks!

**Comment by roylly** [comment]
AMapLocationKit有对应的动态库：AMapLocationDynamic，
需要你手动修改amap_location_flutter_plugin.podspec中的依赖
s.dependency 'AMapLocationDynamic'

**Comment by araisann** [comment]
@roylly 在修改amap_location_flutter_plugin.podspec的内容，   
把s.dependency 'AMapLocation','~>2.6.7'改为s.dependency 'AMapLocationDynamic'之后，编译运行  
AmapLocationFlutterPlugin.m报错  
`No visible @interface for 'AMapFlutterLocationManager' declares the selector 'setLocationAccuracyMode:'`

**Comment by roylly** [comment]
> @roylly 在修改amap_location_flutter_plugin.podspec的内容，
> 把s.dependency 'AMapLocation','~>2.6.7'改为s.dependency 'AMapLocationDynamic'之后，编译运行
> AmapLocationFlutterPlugin.m报错
> `No visible @interface for 'AMapFlutterLocationManager' declares the selector 'setLocationAccuracyMode:'`

需要升级Xcode到12.0版本，这个是iOS14才新加的方法；

**Comment by araisann** [comment]
@roylly Xcode 12.1，flutter是 1.22.2,，都已经是最新版了。   
下载了项目到本地，除了
```
amap_location_flutter_plugin:  
  path: plugins/amap-location-flutter
```
和权限之外，还要配置一些别的吗？

Android出身，对iOS原生部分不熟悉。
创建的项目语言，iOS部分应该默认用的是swift。

**Comment by araisann** [comment]
报错集中在
```
- (void)getSystemAccuracyAuthorization:(FlutterMethodCall*)call result:(FlutterResult)result {
    if (@available(iOS 14.0, *)) {
        AMapFlutterLocationManager *manager = [self locManagerWithCall:call];
        CLAccuracyAuthorization curacyAuthorization = [manager currentAuthorization];
        result(@(curacyAuthorization));
    }
}
```
```
    if (@available(iOS 14.0, *)) {
        NSNumber *accuracyAuthorizationMode = call.arguments[@"locationAccuracyAuthorizationMode"];
        if (accuracyAuthorizationMode) {
            if ([accuracyAuthorizationMode integerValue] == 0) {
                [manager setLocationAccuracyMode:AMapLocationFullAndReduceAccuracy];
            } else if ([accuracyAuthorizationMode integerValue] == 1) {
                [manager setLocationAccuracyMode:AMapLocationFullAccuracy];
            } else if ([accuracyAuthorizationMode integerValue] == 2) {
                [manager setLocationAccuracyMode:AMapLocationReduceAccuracy];
            }
        }

        NSString *fullAccuracyPurposeKey = call.arguments[@"fullAccuracyPurposeKey"];
        if (fullAccuracyPurposeKey) {
            manager.fullAccuracyPurposeKey = fullAccuracyPurposeKey;
        }
    }
```

注释掉里面的代码，简单的定位好像也不影响。

**Comment by roylly** [comment]
我怀疑你改为s.dependency 'AMapLocationDynamic'之后，下载的AMapLocationDynamic版本不是2.6.7，后面也限制一下版本号；
另外，麻烦提供一下崩溃的手机型号和系统；
原生部分如果没有任何业务逻辑，可以改为用objc，可能兼容问题会少一些；

**Comment by araisann** [comment]
@roylly 确实不是2.6.7  
只能配置到2.6.3。   

`s.dependency 'AMapLocationDynamic','~>2.6.7'  `
pod install会报错   
```
[!] CocoaPods could not find compatible versions for pod "AMapLocationDynamic":
  In Podfile:
    amap_location_flutter_plugin (from `.symlinks/plugins/amap_location_flutter_plugin/ios`) was resolved to 0.0.1, which depends on
      AMapLocationDynamic (~> 2.6.7)

None of your spec sources contain a spec satisfying the dependency: `AMapLocationDynamic (~> 2.6.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by roylly** [comment]
你看错误，不都提示了嘛：执行这个命令，pod install --repo-update。 2.6.3是你pod本地缓存的，需要通过这个来升级repo仓库，下载最新的2.6.7；

**Comment by araisann** [comment]
@roylly 
···
pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AMapLocationDynamic":
  In Podfile:
    amap_location_flutter_plugin (from `.symlinks/plugins/amap_location_flutter_plugin/ios`) was resolved to 0.0.1, which depends on
      AMapLocationDynamic (~> 2.6.7)

None of your spec sources contain a spec satisfying the dependency: `AMapLocationDynamic (~> 2.6.7)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
···


去https://cocoapods.org/  搜索，也是2.6.3。

**Comment by roylly** [comment]
AMapLocationDynamic这个动态库，确实因为没有什么用户使用，后来就停止更新了；
实际上第三方的动态库在苹果APP开发层面，也没有什么优势；
所以，咱们这边为什么一定要用use_frameworks!， 如果这个能去掉，就没有这个链接了静态库的问题了；
咱们先确定问题来源吧！https://www.jianshu.com/p/3d0ae289dee0 看看这个是否有帮助

**Comment by cikichen** [comment]
同样遇到了这个问题，Android调通了高高兴兴，iOS一编译一大堆错

**Comment by idootop** [comment]
重新开下这个issue，这个问题咋解决～～～脑壳疼

**Comment by idootop** [comment]
> 报错集中在
> 
> ```
> - (void)getSystemAccuracyAuthorization:(FlutterMethodCall*)call result:(FlutterResult)result {
>     if (@available(iOS 14.0, *)) {
>         AMapFlutterLocationManager *manager = [self locManagerWithCall:call];
>         CLAccuracyAuthorization curacyAuthorization = [manager currentAuthorization];
>         result(@(curacyAuthorization));
>     }
> }
> ```
> 
> ```
>     if (@available(iOS 14.0, *)) {
>         NSNumber *accuracyAuthorizationMode = call.arguments[@"locationAccuracyAuthorizationMode"];
>         if (accuracyAuthorizationMode) {
>             if ([accuracyAuthorizationMode integerValue] == 0) {
>                 [manager setLocationAccuracyMode:AMapLocationFullAndReduceAccuracy];
>             } else if ([accuracyAuthorizationMode integerValue] == 1) {
>                 [manager setLocationAccuracyMode:AMapLocationFullAccuracy];
>             } else if ([accuracyAuthorizationMode integerValue] == 2) {
>                 [manager setLocationAccuracyMode:AMapLocationReduceAccuracy];
>             }
>         }
> 
>         NSString *fullAccuracyPurposeKey = call.arguments[@"fullAccuracyPurposeKey"];
>         if (fullAccuracyPurposeKey) {
>             manager.fullAccuracyPurposeKey = fullAccuracyPurposeKey;
>         }
>     }
> ```
> 
> 注释掉里面的代码，简单的定位好像也不影响。

只能先这么搞了
