### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by 984409591** [amap-demo/amap-location-flutter#9]
/Users/Cz/Documents/flutter/.pub-cache/git/amap-location-flutter-1e4a3502b6c5832cfa522b4d74044104120f4c27/ios/Classes/AmapLocatio
    nFlutterPlugin.m:86:9: error: use of undeclared identifier 'CLAccuracyAuthorization'
            CLAccuracyAuthorization curacyAuthorization = [manager currentAuthorization];
            ^
    /Users/Cz/Documents/flutter/.pub-cache/git/amap-location-flutter-1e4a3502b6c5832cfa522b4d74044104120f4c27/ios/Classes/AmapLocatio
    nFlutterPlugin.m:87:18: error: use of undeclared identifier 'curacyAuthorization'
            result(@(curacyAuthorization));
                     ^
    /Users/Cz/Documents/flutter/.pub-cache/git/amap-location-flutter-1e4a3502b6c5832cfa522b4d74044104120f4c27/ios/Classes/AmapLocatio
    nFlutterPlugin.m:183:26: error: no visible @interface for 'AMapFlutterLocationManager' declares the selector
    'setLocationAccuracyMode:'
                    [manager setLocationAccuracyMode:AMapLocationFullAndReduceAccuracy];
                     ~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
    /Users/Cz/Documents/flutter/.pub-cache/git/amap-location-flutter-1e4a3502b6c5832cfa522b4d74044104120f4c27/ios/Classes/AmapLocatio
    nFlutterPlugin.m:185:26: error: no visible @interface for 'AMapFlutterLocationManager' declares the selector
    'setLocationAccuracyMode:'
                    [manager setLocationAccuracyMode:AMapLocationFullAccuracy];
                     ~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
    /Users/Cz/Documents/flutter/.pub-cache/git/amap-location-flutter-1e4a3502b6c5832cfa522b4d74044104120f4c27/ios/Classes/AmapLocatio
    nFlutterPlugin.m:187:26: error: no visible @interface for 'AMapFlutterLocationManager' declares the selector
    'setLocationAccuracyMode:'
                    [manager setLocationAccuracyMode:AMapLocationReduceAccuracy];

**Comment by roylly** [comment]
是不是你没有升级xcode,没有iOS14的开发环境，所以没有这个CLAccuracyAuthorization类型

**Comment by roylly** [comment]
其它错误，可能是本地定位SDK的版本不是2.6.7导致的，因为只有这个版本才做了iOS14相关的适配，我们会在后续的依赖中限制SDK的版本号

**Comment by liuxinghudiejie** [comment]
请问什么时候能加上版本限制呢？我没有iOS 14的开发环境，出现了上述的错误

**Comment by jk-zhang** [comment]
我也出现了这个问题

**Comment by jk-zhang** [comment]
我使用的是 AMap_iOS_Loc_Lib_V2.6.7
